#!/bin/bash

# This script will display a random man page to help build familiarity with
# tools not previously encountered.

# TODO complete processing of user path

for i in {1..10}; do
    pathLocation[$i]=$(echo $PATH | cut -d ":" -f $i)
done

function man_up () {
    # Find a candidate command in the first directory of the user's PATH
    # In current version, it is crucial that this is the main /bin of PATH.
    page=$(ls ${pathLocation[i]} | shuf | head -1)
    # If there is no man page for the command, send error to /dev/null and
    # call the function again until one is found
    man $page 2> /dev/null || man_up
    # TODO Add escape in case there are no candidates in directory
}

man_up
